const SUPPORTED_WEBHOOK_EVENTS = [
  'APP_PURCHASES_ONE_TIME_UPDATE',
  'APP_SUBSCRIPTIONS_APPROACHING_CAPPED_AMOUNT',
  'APP_SUBSCRIPTIONS_UPDATE',
  'APP_UNINSTALLED',
  'ATTRIBUTED_SESSIONS_FIRST',
  'ATTRIBUTED_SESSIONS_LAST',
  'AUDIT_EVENTS_ADMIN_API_ACTIVITY',
  'BULK_OPERATIONS_FINISH',
  'CARTS_CREATE',
  'CARTS_UPDATE',
  'CHANNELS_DELETE',
  'CHECKOUTS_CREATE',
  'CHECKOUTS_DELETE',
  'CHECKOUTS_UPDATE',
  'COLLECTION_LISTINGS_ADD',
  'COLLECTION_LISTINGS_REMOVE',
  'COLLECTION_LISTINGS_UPDATE',
  'COLLECTION_PUBLICATIONS_CREATE',
  'COLLECTION_PUBLICATIONS_DELETE',
  'COLLECTION_PUBLICATIONS_UPDATE',
  'COLLECTIONS_CREATE',
  'COLLECTIONS_DELETE',
  'COLLECTIONS_UPDATE',
  'COMPANIES_CREATE',
  'COMPANIES_DELETE',
  'COMPANIES_UPDATE',
  'COMPANY_CONTACT_ROLES_ASSIGN',
  'COMPANY_CONTACT_ROLES_REVOKE',
  'COMPANY_CONTACTS_CREATE',
  'COMPANY_CONTACTS_DELETE',
  'COMPANY_CONTACTS_UPDATE',
  'COMPANY_LOCATIONS_CREATE',
  'COMPANY_LOCATIONS_DELETE',
  'COMPANY_LOCATIONS_UPDATE',
  'CUSTOMER_GROUPS_CREATE',
  'CUSTOMER_GROUPS_DELETE',
  'CUSTOMER_GROUPS_UPDATE',
  'CUSTOMER_PAYMENT_METHODS_CREATE',
  'CUSTOMER_PAYMENT_METHODS_REVOKE',
  'CUSTOMER_PAYMENT_METHODS_UPDATE',
  'CUSTOMER_TAGS_ADDED',
  'CUSTOMER_TAGS_REMOVED',
  'CUSTOMERS_CREATE',
  'CUSTOMERS_DELETE',
  'CUSTOMERS_DISABLE',
  'CUSTOMERS_EMAIL_MARKETING_CONSENT_UPDATE',
  'CUSTOMERS_ENABLE',
  'CUSTOMERS_MARKETING_CONSENT_UPDATE',
  'CUSTOMERS_MERGE',
  'CUSTOMERS_UPDATE',
  'DISPUTES_CREATE',
  'DISPUTES_UPDATE',
  'DOMAINS_CREATE',
  'DOMAINS_DESTROY',
  'DOMAINS_UPDATE',
  'DRAFT_ORDERS_CREATE',
  'DRAFT_ORDERS_DELETE',
  'DRAFT_ORDERS_UPDATE',
  'FULFILLMENT_EVENTS_CREATE',
  'FULFILLMENT_EVENTS_DELETE',
  'FULFILLMENT_ORDERS_CANCELLATION_REQUEST_ACCEPTED',
  'FULFILLMENT_ORDERS_CANCELLATION_REQUEST_REJECTED',
  'FULFILLMENT_ORDERS_CANCELLATION_REQUEST_SUBMITTED',
  'FULFILLMENT_ORDERS_CANCELLED',
  'FULFILLMENT_ORDERS_FULFILLMENT_REQUEST_ACCEPTED',
  'FULFILLMENT_ORDERS_FULFILLMENT_REQUEST_REJECTED',
  'FULFILLMENT_ORDERS_FULFILLMENT_REQUEST_SUBMITTED',
  'FULFILLMENT_ORDERS_FULFILLMENT_SERVICE_FAILED_TO_COMPLETE',
  'FULFILLMENT_ORDERS_HOLD_RELEASED',
  'FULFILLMENT_ORDERS_LINE_ITEMS_PREPARED_FOR_LOCAL_DELIVERY',
  'FULFILLMENT_ORDERS_LINE_ITEMS_PREPARED_FOR_PICKUP',
  'FULFILLMENT_ORDERS_MOVED',
  'FULFILLMENT_ORDERS_ORDER_ROUTING_COMPLETE',
  'FULFILLMENT_ORDERS_PLACED_ON_HOLD',
  'FULFILLMENT_ORDERS_RESCHEDULED',
  'FULFILLMENT_ORDERS_SCHEDULED_FULFILLMENT_ORDER_READY',
  'FULFILLMENTS_CREATE',
  'FULFILLMENTS_UPDATE',
  'INVENTORY_ITEMS_CREATE',
  'INVENTORY_ITEMS_DELETE',
  'INVENTORY_ITEMS_UPDATE',
  'INVENTORY_LEVELS_CONNECT',
  'INVENTORY_LEVELS_DISCONNECT',
  'INVENTORY_LEVELS_UPDATE',
  'LOCALES_CREATE',
  'LOCALES_UPDATE',
  'LOCATIONS_ACTIVATE',
  'LOCATIONS_CREATE',
  'LOCATIONS_DEACTIVATE',
  'LOCATIONS_DELETE',
  'LOCATIONS_UPDATE',
  'MARKETS_CREATE',
  'MARKETS_DELETE',
  'MARKETS_UPDATE',
  'moved_fulfillment_order',
  'ORDER_TRANSACTIONS_CREATE',
  'ORDERS_CANCELLED',
  'ORDERS_CREATE',
  'ORDERS_DELETE',
  'ORDERS_EDITED',
  'ORDERS_FULFILLED',
  'ORDERS_PAID',
  'ORDERS_PARTIALLY_FULFILLED',
  'ORDERS_UPDATED',
  'original_fulfillment_order',
  'PAYMENT_SCHEDULES_DUE',
  'PAYMENT_TERMS_CREATE',
  'PAYMENT_TERMS_DELETE',
  'PAYMENT_TERMS_UPDATE',
  'PRODUCT_FEEDS_CREATE',
  'PRODUCT_FEEDS_FULL_SYNC',
  'PRODUCT_FEEDS_INCREMENTAL_SYNC',
  'PRODUCT_FEEDS_UPDATE',
  'PRODUCT_LISTINGS_ADD',
  'PRODUCT_LISTINGS_REMOVE',
  'PRODUCT_LISTINGS_UPDATE',
  'PRODUCT_PUBLICATIONS_CREATE',
  'PRODUCT_PUBLICATIONS_DELETE',
  'PRODUCT_PUBLICATIONS_UPDATE',
  'PRODUCTS_CREATE',
  'PRODUCTS_DELETE',
  'PRODUCTS_UPDATE',
  'PROFILES_CREATE',
  'PROFILES_DELETE',
  'PROFILES_UPDATE',
  'REFUNDS_CREATE',
  'RETURNS_APPROVE',
  'RETURNS_CANCEL',
  'RETURNS_CLOSE',
  'RETURNS_DECLINE',
  'RETURNS_REOPEN',
  'RETURNS_REQUEST',
  'REVERSE_DELIVERIES_ATTACH_DELIVERABLE',
  'REVERSE_FULFILLMENT_ORDERS_DISPOSE',
  'SCHEDULED_PRODUCT_LISTINGS_ADD',
  'SCHEDULED_PRODUCT_LISTINGS_REMOVE',
  'SCHEDULED_PRODUCT_LISTINGS_UPDATE',
  'SEGMENTS_CREATE',
  'SEGMENTS_DELETE',
  'SEGMENTS_UPDATE',
  'SELLING_PLAN_GROUPS_CREATE',
  'SELLING_PLAN_GROUPS_DELETE',
  'SELLING_PLAN_GROUPS_UPDATE',
  'SHIPPING_ADDRESSES_CREATE',
  'SHIPPING_ADDRESSES_UPDATE',
  'SHOP_UPDATE',
  'source_location',
  'SUBSCRIPTION_BILLING_ATTEMPTS_CHALLENGED',
  'SUBSCRIPTION_BILLING_ATTEMPTS_FAILURE',
  'SUBSCRIPTION_BILLING_ATTEMPTS_SUCCESS',
  'SUBSCRIPTION_BILLING_CYCLE_EDITS_CREATE',
  'SUBSCRIPTION_BILLING_CYCLE_EDITS_DELETE',
  'SUBSCRIPTION_BILLING_CYCLE_EDITS_UPDATE',
  'SUBSCRIPTION_CONTRACTS_CREATE',
  'SUBSCRIPTION_CONTRACTS_UPDATE',
  'TAX_PARTNERS_UPDATE',
  'TAX_SERVICES_CREATE',
  'TAX_SERVICES_UPDATE',
  'TENDER_TRANSACTIONS_CREATE',
];

class ApiEaseWebhookEventService {
  constructor({ supportedWebhookEvents = SUPPORTED_WEBHOOK_EVENTS } = {}) {
    this.supportedWebhookEvents = supportedWebhookEvents;
    this.supportedWebhookEventSet = new Set(supportedWebhookEvents);
  }

  normalizeWebhookEvent(webhookEvent) {
    if (typeof webhookEvent !== 'string') {
      return webhookEvent;
    }

    const trimmedWebhookEvent = webhookEvent.trim();
    if (trimmedWebhookEvent.length === 0 || this.supportedWebhookEventSet.has(trimmedWebhookEvent)) {
      return trimmedWebhookEvent;
    }

    return trimmedWebhookEvent.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '').toUpperCase();
  }

  isSupportedWebhookEvent(webhookEvent) {
    return this.supportedWebhookEventSet.has(webhookEvent);
  }

  isValidWebhookEvent(webhookEvent) {
    return this.isSupportedWebhookEvent(this.normalizeWebhookEvent(webhookEvent));
  }

  normalizeRequestWebhookEvents(request) {
    if (!this.isPlainObject(request) || !Array.isArray(request.triggers)) {
      return request;
    }

    return {
      ...request,
      triggers: request.triggers.map((trigger) => this.normalizeTriggerWebhookEvent(trigger)),
    };
  }

  normalizeTriggerWebhookEvent(trigger) {
    if (!this.isPlainObject(trigger) || trigger.type !== 'webhook' || !this.isPlainObject(trigger.webhook)) {
      return trigger;
    }

    return {
      ...trigger,
      webhook: {
        ...trigger.webhook,
        event: this.normalizeWebhookEvent(trigger.webhook.event),
      },
    };
  }

  isPlainObject(value) {
    return typeof value === 'object' && value !== null && !Array.isArray(value);
  }
}

export { ApiEaseWebhookEventService };
